name: CI Quality Assurance

on: [push, pull_request]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout@v3
        uses: actions/checkout@v3

      - name: Configurar Ambiente Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Dependências do Sistema
        run: |
          pip install Flask pytest flake8

      - name: Execução da Suíte de Testes Automatizados (Pytest)
        run: |
          pytest tests/